/*
 * Faze.Examples.Gallery.API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Visualisation struct {
	Id   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
